# Generated by Django 6.0.1 on 2026-01-09 19:05

import apps.profile_app.models.link
import apps.profile_app.models.page
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profile_app.models.link.link_icon_path),
        ),
        migrations.AlterField(
            model_name='page',
            name='banner_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profile_app.models.page.banner_picture_path),
        ),
        migrations.AlterField(
            model_name='page',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profile_app.models.page.profile_picture_path),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('button_color', models.CharField(default='#3b82f6', max_length=7)),
                ('button_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_family', models.CharField(default='Inter', max_length=50)),
                ('border_radius', models.PositiveIntegerField(default=8)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='profile_app.template'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['user'], name='profile_app_user_id_4fb79b_idx'),
        ),
    ]
